.TH socketcand 1 "JANUARY 2011" Linux "User Manuals"
.SH NAME
socketcand \- The Socket CAN daemon
.SH SYNOPSIS
.B socketcand [-v | --verbose] [-i 
.I interfaces 
.B | --interfaces 
.I interfaces
.B ] [-p 
.I port 
.B | --port 
.I port
.B ] [-l 
.I interface 
.B | --listen 
.I interface
.B ] [-d | --daemon ] [-n | --no-beacon]
.SH DESCRIPTION
.B socketcand
is a daemon that provides access to CAN interfaces on a machine via a network interface. The communication protocol uses a TCP/IP connection and a specific protocol to transfer CAN frames and control commands.
.SH OPTIONS
.IP -v
activates verbose output
.IP -i
comma separated list of SocketCAN interfaces the daemon shall provide access to (e.g. -i can0,vcan1)
.IP -p
port changes the default port (29536) the daemon is listening at
.IP -l
interface changes the default interface (eth0) the daemon will bind to
.IP -d
set this flag if you want log to syslog instead of STDOUT
.IP -n
disables the discovery beacon
.IP -h
prints a help message
