#! /bin/sh

### BEGIN INIT INFO
# Provides:          socketcand
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: socketcand
# Description:       daemon that provides network access to local CAN busses
### END INIT INFO

. /lib/lsb/init-functions

[ -f /etc/default/rcS ] && . /etc/default/rcS
PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/local/bin/socketcand
DESC="SocketCAN daemon"
NAME="socketcand"
PIDFILE=/var/run/socketcand.pid
#CONF=/etc/fancontrol

test -x $DAEMON || exit 0

case "$1" in
  start)
	log_daemon_msg "Starting $DESC" "$NAME"
	start-stop-daemon --start --quiet --background --pidfile $PIDFILE --startas $DAEMON -m -- --daemon
	log_end_msg $?
	;;
  stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
	start-stop-daemon --stop --quiet --pidfile $PIDFILE --oknodo --startas $DAEMON
	rm -f $PIDFILE
	log_end_msg $?
	;;
  restart)
  	$0 stop
	sleep 3
	$0 start
	;;
  force-reload)
	if start-stop-daemon --stop --test --quiet --pidfile $PIDFILE --startas $DAEMON ; then
		$0 restart
	fi
	;;
  status)
	status_of_proc $DAEMON $NAME && exit 0 || exit $?
	;;
  *)
	log_success_msg "Usage: /etc/init.d/socketcand {start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
